### PR TITLE
feat: delete bug fix check and warning message after edit pr title

### PR DESCRIPTION
**Pull request by teodorus-nathaniel**
resolves: #318 

## Summary by CodeRabbit

- **New Features**
	- Introduced new asynchronous functions for updating and deleting GitHub check runs.
	- Enhanced logic for managing check runs based on pull request title changes.

- **Bug Fixes**
	- Streamlined comment handling for submissions and bug reports to improve clarity and efficiency.

- **Refactor**
	- Removed unused type imports and local functions to consolidate functionality related to check runs.

### CODE REVIEW

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Please resolve conflicts and  check my comment from here: https://github.com/holdex/pr-time-tracker/pull/317

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel I want to see the comment (message) to add bug author, and the comment with bug author here in this PR

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel please use git blame and specify the link to the commit link that has introduced this bug. Send the following message in this PR: `@pr-time-tracker bug commit [link] && bug author @name`

There's the message, and its also already sticky like the submission comment

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel please use git blame and specify the link to the commit link that has introduced this bug. Send the following message in this PR: `@pr-time-tracker bug commit [link] && bug author @name`

There's the message, and its also already sticky like the submission comment

**Comment by teodorus-nathaniel** [comment]
test message

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel go ahead

**Comment by teodorus-nathaniel** [comment]
@pr-time-tracker bug commit [c79af9e](https://github.com/holdex/pr-time-tracker/pull/319/commits/c79af9e2a70fde2b70361fa06ce6c861fdae8607) && bug author @teodorus-nathaniel

**Comment by teodorus-nathaniel** [comment]
@pr-time-tracker bug commit [c79af9e](https://github.com/holdex/pr-time-tracker/pull/319/commits/c79af9e2a70fde2b70361fa06ce6c861fdae8607) && bug author @teodorus-nathaniel

**Comment by teodorus-nathaniel** [comment]
@pr-time-tracker bug commit [c79af9e](https://github.com/holdex/pr-time-tracker/pull/319/commits/c79af9e2a70fde2b70361fa06ce6c861fdae8607) && bug author @teodorus-nathaniel

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru updated, tried 3 times because I forgot to turn on proxy and remove the early return `dummy` in the code 😅

**Comment by teodorus-nathaniel** [comment]
For step 2:
image

**Comment by teodorus-nathaniel** [comment]
New message to trigger the action again
(Now delete message doesn't trigger the events yet, Ill added it in the other branch, for the next PR)

**Comment by teodorus-nathaniel** [comment]
Step 3:
image

**Comment by teodorus-nathaniel** [comment]
Step 4:
I changed back the title to `feat:`
- warning message deleted
- action becomes neutral
image

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru all good?

**Comment by markholdex** [comment]
> @georgeciubotaru all good?

@teodorus-nathaniel Should we even leave this info and display it was cancelled? Should we remove it completely?

**Comment by teodorus-nathaniel** [comment]
@markholdex I searched about it and can't find a way to remove it, github only allows actions to be updated

**Comment by teodorus-nathaniel** [comment]
> > @georgeciubotaru all good?
> 
> @teodorus-nathaniel Should we even leave this info and display it was cancelled? Should we remove it completely?

From what I find, it seems not possible to delete an already existing check runs, I searched the docs and based on the github docs and octokit docs, it seems there is no api to delete existing check

**Pull request merged**
